name: 'ECS Rollback'
description: 'Rollback ECS services to previous image tags'

inputs:
  terraform_path:
    description: 'Path to Terraform directory'
    required: true
  previous_image_tag:
    description: 'Previous image tag to rollback to'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  var_files:
    description: 'Space-separated list of var file names (default: "terraform.tfvars services.generated.tfvars")'
    required: false
    default: 'terraform.tfvars services.generated.tfvars'

outputs:
  rolled_back:
    description: 'Whether rollback was successful (true/false)'
    value: ${{ steps.rollback.outputs.rolled_back }}

runs:
  using: 'composite'
  steps:
    - name: Rollback to previous image tags
      id: rollback
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws_region }}
      run: |
        if [ -z "${{ inputs.previous_image_tag }}" ]; then
          echo "::error::No previous image tag provided. Cannot rollback."
          echo "rolled_back=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        echo "::notice::Rolling back to previous image tag: ${{ inputs.previous_image_tag }}"
        
        # Get service keys (not names) from Terraform outputs
        SERVICE_NAMES_JSON=$(terraform -chdir="${{ inputs.terraform_path }}" output -json service_names 2>/dev/null || echo "{}")
        
        if [ "$SERVICE_NAMES_JSON" = "{}" ] || [ "$SERVICE_NAMES_JSON" = "null" ]; then
          echo "::error::Could not determine service keys from Terraform outputs"
          echo "rolled_back=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        # Build service_tags JSON object for update script
        SERVICE_TAGS_JSON="{"
        FIRST=true
        for service_key in $(echo "$SERVICE_NAMES_JSON" | jq -r 'keys[]'); do
          if [ "$FIRST" = true ]; then
            FIRST=false
          else
            SERVICE_TAGS_JSON="$SERVICE_TAGS_JSON,"
          fi
          SERVICE_TAGS_JSON="$SERVICE_TAGS_JSON\"$service_key\":\"${{ inputs.previous_image_tag }}\""
        done
        SERVICE_TAGS_JSON="$SERVICE_TAGS_JSON}"
        
        echo "::notice::Rolling back image tags in services.generated.tfvars"
        echo "::notice::Previous image tag: ${{ inputs.previous_image_tag }}"
        
        # Update image tags directly in services.generated.tfvars
        python scripts/update_service_image_tags.py \
          --tfvars-file "${{ inputs.terraform_path }}/services.generated.tfvars" \
          --service-tags "$SERVICE_TAGS_JSON"
        
        echo "::notice::✓ Updated services.generated.tfvars with rollback image tags"
        
        # Apply rollback
        cd "${{ inputs.terraform_path }}"
        
        APPLY_ARGS="-auto-approve"
        
        # Add var files if provided
        if [ -n "${{ inputs.var_files }}" ]; then
          for var_file in ${{ inputs.var_files }}; do
            if [ -f "$var_file" ]; then
              APPLY_ARGS="$APPLY_ARGS -var-file=$var_file"
            fi
          done
        fi
        
        echo "::notice::Applying rollback configuration..."
        terraform apply $APPLY_ARGS
        
        if [ $? -eq 0 ]; then
          echo "✅ Rollback applied successfully"
          
          # Wait for services to stabilize
          CLUSTER_NAME=$(terraform output -raw ecs_cluster_name 2>/dev/null || echo "")
          SERVICES=$(echo "$SERVICE_NAMES_JSON" | jq -r 'to_entries[] | .value')
          
          if [ -n "$CLUSTER_NAME" ] && [ "$CLUSTER_NAME" != "null" ]; then
            echo "::notice::Waiting for services to stabilize after rollback..."
            aws ecs wait services-stable \
              --region ${AWS_REGION} \
              --cluster "$CLUSTER_NAME" \
              --services $SERVICES || {
              echo "::warning::Services did not stabilize after rollback, but rollback was applied"
            }
          fi
          
          echo "rolled_back=true" >> $GITHUB_OUTPUT
        else
          echo "::error::Rollback failed"
          echo "rolled_back=false" >> $GITHUB_OUTPUT
          exit 1
        fi

