#!/bin/bash
# Generate per-application docker-compose files
# This creates docker-compose.yml files in each application directory (best practice)
# Usage: ./scripts/generate-app-compose.sh [app-name] [--prod]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROD="${2:-}"

if [ -n "${1:-}" ] && [ "${1:-}" != "--prod" ]; then
  # Generate for specific app
  APP_NAME="$1"
  APPS=("$APP_NAME")
  if [ "${2:-}" = "--prod" ]; then
    PROD="--prod"
  fi
else
  # Generate for all apps
  APPS=($(find "$BASE_DIR/applications" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;))
  if [ "${1:-}" = "--prod" ]; then
    PROD="--prod"
  fi
fi

for APP_NAME in "${APPS[@]}"; do
  APP_DIR="$BASE_DIR/applications/$APP_NAME"
  
  if [ ! -d "$APP_DIR" ]; then
    echo "::warning::Application directory not found: $APP_DIR"
    continue
  fi
  
  # Generate to app directory (best practice: co-located with app code)
  if [ -n "$PROD" ]; then
    OUTPUT_FILE="$APP_DIR/docker-compose.prod.yml"
  else
    OUTPUT_FILE="$APP_DIR/docker-compose.yml"
  fi
  APP_NAME_UPPER=$(echo "$APP_NAME" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
  
  echo "# Application-specific docker-compose for: $APP_NAME" > "$OUTPUT_FILE"
  echo "# Auto-generated by scripts/generate-app-compose.sh" >> "$OUTPUT_FILE"
  echo "# DO NOT EDIT MANUALLY - regenerate with: ./scripts/generate-app-compose.sh $APP_NAME${PROD:+ --prod}" >> "$OUTPUT_FILE"
  echo "#" >> "$OUTPUT_FILE"
  echo "# Usage from root:" >> "$OUTPUT_FILE"
  echo "#   docker compose -f docker-compose.base.yml -f applications/$APP_NAME/docker-compose.yml up" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "version: '3.8'" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "services:" >> "$OUTPUT_FILE"
  
  # Backend service
  if [ -d "$APP_DIR/backend" ] && [ -f "$APP_DIR/backend/Dockerfile" ]; then
    if [ -z "$PROD" ]; then
      # Development: build from source
      cat >> "$OUTPUT_FILE" << EOF
  ${APP_NAME}-backend:
    build:
      context: ./applications/${APP_NAME}/backend
      dockerfile: Dockerfile
      args:
        BUILD_DATE: \${BUILD_DATE:-2024-01-01T00:00:00Z}
        BUILD_VERSION: \${BUILD_VERSION:-dev}
        GIT_COMMIT: \${GIT_COMMIT:-unknown}
        GIT_BRANCH: \${GIT_BRANCH:-main}
    image: ${APP_NAME}-backend:\${BUILD_VERSION:-dev}
EOF
    else
      # Production: use image from registry
      cat >> "$OUTPUT_FILE" << EOF
  ${APP_NAME}-backend:
    image: \${${APP_NAME_UPPER}_BACKEND_IMAGE:-ghcr.io/orshalit/${APP_NAME}-backend:latest}
EOF
    fi
    
    cat >> "$OUTPUT_FILE" << EOF
    container_name: ${APP_NAME}-backend
    ports:
      - "\${${APP_NAME_UPPER}_BACKEND_PORT:-8000}:8000"
    environment:
      DATABASE_URL: postgresql://\${POSTGRES_USER:-appuser}:\${POSTGRES_PASSWORD:-apppassword}@database:5432/\${POSTGRES_DB:-appdb}
      LOG_LEVEL: \${LOG_LEVEL:-INFO}
EOF
    
    if [ -z "$PROD" ]; then
      echo "      RATE_LIMIT_ENABLED: \${RATE_LIMIT_ENABLED:-false}" >> "$OUTPUT_FILE"
    else
      echo "      LOG_FORMAT: \${LOG_FORMAT:-json}" >> "$OUTPUT_FILE"
      echo "      RATE_LIMIT_ENABLED: \${RATE_LIMIT_ENABLED:-true}" >> "$OUTPUT_FILE"
    fi
    
    cat >> "$OUTPUT_FILE" << EOF
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
EOF
    
    if [ -n "$PROD" ]; then
      echo "    logging:" >> "$OUTPUT_FILE"
      echo "      driver: \"json-file\"" >> "$OUTPUT_FILE"
      echo "      options:" >> "$OUTPUT_FILE"
      echo "        max-size: \"10m\"" >> "$OUTPUT_FILE"
      echo "        max-file: \"3\"" >> "$OUTPUT_FILE"
    fi
  fi
  
  # Frontend service
  if [ -d "$APP_DIR/frontend" ] && [ -f "$APP_DIR/frontend/Dockerfile" ]; then
    if [ -z "$PROD" ]; then
      # Development: build from source
      cat >> "$OUTPUT_FILE" << EOF
  ${APP_NAME}-frontend:
    build:
      context: ./applications/${APP_NAME}/frontend
      dockerfile: Dockerfile
      args:
        BUILD_DATE: \${BUILD_DATE:-2024-01-01T00:00:00Z}
        BUILD_VERSION: \${BUILD_VERSION:-dev}
        GIT_COMMIT: \${GIT_COMMIT:-unknown}
        GIT_BRANCH: \${GIT_BRANCH:-main}
    image: ${APP_NAME}-frontend:\${BUILD_VERSION:-dev}
EOF
    else
      # Production: use image from registry
      cat >> "$OUTPUT_FILE" << EOF
  ${APP_NAME}-frontend:
    image: \${${APP_NAME_UPPER}_FRONTEND_IMAGE:-ghcr.io/orshalit/${APP_NAME}-frontend:latest}
EOF
    fi
    
    cat >> "$OUTPUT_FILE" << EOF
    container_name: ${APP_NAME}-frontend
    ports:
      - "\${${APP_NAME_UPPER}_FRONTEND_PORT:-3000}:3000"
    environment:
      VITE_BACKEND_URL: \${${APP_NAME_UPPER}_BACKEND_URL:-http://${APP_NAME}-backend:8000}
    depends_on:
      ${APP_NAME}-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
EOF
    
    if [ -n "$PROD" ]; then
      echo "    logging:" >> "$OUTPUT_FILE"
      echo "      driver: \"json-file\"" >> "$OUTPUT_FILE"
      echo "      options:" >> "$OUTPUT_FILE"
      echo "        max-size: \"10m\"" >> "$OUTPUT_FILE"
      echo "        max-file: \"3\"" >> "$OUTPUT_FILE"
    fi
  fi
  
  echo "✓ Generated $OUTPUT_FILE"
done

