#!/bin/bash
# Generate docker-compose.yml dynamically from application structure
# This script scans applications/ directory and generates docker-compose.yml
# that works for local development with any number of applications.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROD="${1:-}"

OUTPUT_FILE="$BASE_DIR/docker-compose${PROD:+.prod}.yml"

echo "# $(if [ -n "$PROD" ]; then echo "Production"; else echo "Development"; fi) docker-compose.yml" > "$OUTPUT_FILE"
echo "# Auto-generated by scripts/generate-docker-compose.sh" >> "$OUTPUT_FILE"
echo "# DO NOT EDIT MANUALLY - regenerate with: ./scripts/generate-docker-compose.sh${PROD:+ --prod}" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "version: '3.8'" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "services:" >> "$OUTPUT_FILE"

# Add database service
cat >> "$OUTPUT_FILE" << 'DBEOF'
  database:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
DBEOF

if [ -n "$PROD" ]; then
  echo "    logging:" >> "$OUTPUT_FILE"
  echo "      driver: \"json-file\"" >> "$OUTPUT_FILE"
  echo "      options:" >> "$OUTPUT_FILE"
  echo "        max-size: \"10m\"" >> "$OUTPUT_FILE"
  echo "        max-file: \"3\"" >> "$OUTPUT_FILE"
fi

# Find all applications with backend/frontend
for APP_DIR in "$BASE_DIR/applications"/*/; do
  if [ ! -d "$APP_DIR" ]; then
    continue
  fi
  
  APP_NAME=$(basename "$APP_DIR")
  APP_NAME_UPPER=$(echo "$APP_NAME" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
  
  # Backend service
  if [ -d "$APP_DIR/backend" ] && [ -f "$APP_DIR/backend/Dockerfile" ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "  ${APP_NAME}-backend:" >> "$OUTPUT_FILE"
    
    if [ -z "$PROD" ]; then
      # Development: build from source
      cat >> "$OUTPUT_FILE" << EOF
    build:
      context: ./applications/${APP_NAME}/backend
      dockerfile: Dockerfile
      args:
        BUILD_DATE: \${BUILD_DATE:-2024-01-01T00:00:00Z}
        BUILD_VERSION: \${BUILD_VERSION:-dev}
        GIT_COMMIT: \${GIT_COMMIT:-unknown}
        GIT_BRANCH: \${GIT_BRANCH:-main}
    image: ${APP_NAME}-backend:\${BUILD_VERSION:-dev}
EOF
    else
      # Production: use image from registry
      cat >> "$OUTPUT_FILE" << EOF
    image: \${${APP_NAME_UPPER}_BACKEND_IMAGE:-ghcr.io/orshalit/${APP_NAME}-backend:latest}
EOF
    fi
    
    cat >> "$OUTPUT_FILE" << EOF
    container_name: ${APP_NAME}-backend
    ports:
      - "\${${APP_NAME_UPPER}_BACKEND_PORT:-8000}:8000"
    environment:
      DATABASE_URL: postgresql://\${POSTGRES_USER:-appuser}:\${POSTGRES_PASSWORD:-apppassword}@database:5432/\${POSTGRES_DB:-appdb}
      LOG_LEVEL: \${LOG_LEVEL:-INFO}
EOF
    
    if [ -z "$PROD" ]; then
      echo "      RATE_LIMIT_ENABLED: \${RATE_LIMIT_ENABLED:-false}" >> "$OUTPUT_FILE"
    else
      echo "      LOG_FORMAT: \${LOG_FORMAT:-json}" >> "$OUTPUT_FILE"
      echo "      RATE_LIMIT_ENABLED: \${RATE_LIMIT_ENABLED:-true}" >> "$OUTPUT_FILE"
    fi
    
    cat >> "$OUTPUT_FILE" << EOF
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
EOF
    
    if [ -n "$PROD" ]; then
      echo "    logging:" >> "$OUTPUT_FILE"
      echo "      driver: \"json-file\"" >> "$OUTPUT_FILE"
      echo "      options:" >> "$OUTPUT_FILE"
      echo "        max-size: \"10m\"" >> "$OUTPUT_FILE"
      echo "        max-file: \"3\"" >> "$OUTPUT_FILE"
    fi
  fi
  
  # Frontend service
  if [ -d "$APP_DIR/frontend" ] && [ -f "$APP_DIR/frontend/Dockerfile" ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "  ${APP_NAME}-frontend:" >> "$OUTPUT_FILE"
    
    if [ -z "$PROD" ]; then
      # Development: build from source
      cat >> "$OUTPUT_FILE" << EOF
    build:
      context: ./applications/${APP_NAME}/frontend
      dockerfile: Dockerfile
      args:
        BUILD_DATE: \${BUILD_DATE:-2024-01-01T00:00:00Z}
        BUILD_VERSION: \${BUILD_VERSION:-dev}
        GIT_COMMIT: \${GIT_COMMIT:-unknown}
        GIT_BRANCH: \${GIT_BRANCH:-main}
    image: ${APP_NAME}-frontend:\${BUILD_VERSION:-dev}
EOF
    else
      # Production: use image from registry
      cat >> "$OUTPUT_FILE" << EOF
    image: \${${APP_NAME_UPPER}_FRONTEND_IMAGE:-ghcr.io/orshalit/${APP_NAME}-frontend:latest}
EOF
    fi
    
    cat >> "$OUTPUT_FILE" << EOF
    container_name: ${APP_NAME}-frontend
    ports:
      - "\${${APP_NAME_UPPER}_FRONTEND_PORT:-3000}:3000"
    environment:
      VITE_BACKEND_URL: \${${APP_NAME_UPPER}_BACKEND_URL:-http://${APP_NAME}-backend:8000}
    depends_on:
      ${APP_NAME}-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
EOF
    
    if [ -n "$PROD" ]; then
      echo "    logging:" >> "$OUTPUT_FILE"
      echo "      driver: \"json-file\"" >> "$OUTPUT_FILE"
      echo "      options:" >> "$OUTPUT_FILE"
      echo "        max-size: \"10m\"" >> "$OUTPUT_FILE"
      echo "        max-file: \"3\"" >> "$OUTPUT_FILE"
    fi
  fi
done

# Add networks and volumes
cat >> "$OUTPUT_FILE" << 'NETEOF'

networks:
  app-network:
    driver: bridge
NETEOF

if [ -n "$PROD" ]; then
  echo "    ipam:" >> "$OUTPUT_FILE"
  echo "      config:" >> "$OUTPUT_FILE"
  echo "        - subnet: 172.20.0.0/16" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << 'VOLEOF'

volumes:
  postgres_data:
VOLEOF

if [ -n "$PROD" ]; then
  echo "    driver: local" >> "$OUTPUT_FILE"
fi

echo "✓ Generated $OUTPUT_FILE"
echo "  Applications detected: $(find "$BASE_DIR/applications" -mindepth 1 -maxdepth 1 -type d | wc -l)"

